version: 1.0.{build}

#init:
#- ps: Update-AppveyorBuild -Version "0.0.$env:appveyor_build_number-$($env:appveyor_repo_commit.substring(0,7))"

#install:
#- echo %appveyor_build_version%

xamarin:
  email: feodor@appveyor.com
  password:
    secure: KPaIpDJc143PUza6qBdpWQ==
  ios: true

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
test: off


#deploy:
#- provider: NuGet
#  api_key:
#    secure: 5MUShxp5+kPsKeKnl2gHSniQOJQ5/B8REh4nH2LfTi7AwA1oUHulT1Apl9eR+hQs
#- provider: NuGet
#  api_key:
#    secure: 5MUShxp5+kPsKeKnl2gHSniQOJQ5/B8REh4nH2LfTi7AwA1oUHulT1Apl9eR+hQs

#notifications:
#- provider: Slack
#  incoming_webhook: https://hooks.slack.com/services/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11
#  auth_token: ''
#  on_build_success: false
#  on_build_failure: false
#  on_build_status_changed: true 
