version: 1.0.{build}-rc2

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
test: off
