assembly_info:
  patch: true

before_build:
  - echo %APPVEYOR_PULL_REQUEST_NUMBER%

nuget:
  disable_publish_on_pr: true

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  api_key: -none-
  on:
    appveyor_repo_tag: true
