version: 1.1.{build}-{branch}

shallow_clone: true

install:
  - ps: Update-AppveyorBuild -Version '1.1.1-test'

assembly_info:
  patch: true

before_build:
  - echo %APPVEYOR_BUILD_VERSION%

nuget:
  disable_publish_on_pr: true

build:
  publish_nuget: true

