version: 1.0.{build}

assembly_info: 
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "{version}" 
  assembly_file_version: "{version}" 
  assembly_informational_version: "{version}"

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
test: off

#deploy:
#- provider: NuGet
#  api_key:
#    secure: 5MUShxp5+kPsKeKnl2gHSniQOJQ5/B8REh4nH2LfTi7AwA1oUHulT1Apl9eR+hQs
#- provider: NuGet
#  api_key:
#    secure: 5MUShxp5+kPsKeKnl2gHSniQOJQ5/B8REh4nH2LfTi7AwA1oUHulT1Apl9eR+hQs
